#{{ if ne .Values.service.image.tag "localbuild" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Release.Name }}-docker-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: DOCKER_CONFIG_JSON
          key: .dockerconfigjson
    - secretName: {{ .Release.Name }}
      type: Opaque
      data:
        - objectName: KAFKA_API_KEY
          key: KAFKA_API_KEY
        - objectName: KAFKA_API_SECRET
          key: KAFKA_API_SECRET
        - objectName: SCHEMA_REGISTRY_API_KEY
          key: SCHEMA_REGISTRY_API_KEY
        - objectName: SCHEMA_REGISTRY_API_SECRET
          key: SCHEMA_REGISTRY_API_SECRET
        - objectName: SCHEMA_REGISTRY_URI
          key: SCHEMA_REGISTRY_URI
        - objectName: NEW_RELIC_LICENSE_KEY
          key: NEW_RELIC_LICENSE_KEY
        - objectName: RDS_DB_USERNAME
          key: RDS_DB_USERNAME
        - objectName: RDS_DB_PASSWORD
          key: RDS_DB_PASSWORD
  parameters:
    region: us-east-2
    objects: |   
      - objectName: "foundation/dockerconfigjson"
        objectAlias: "DOCKER_CONFIG_JSON"
        objectType: "secretsmanager"
      - objectName: "CONFLUENT/SA/dp-person-registry"
        jmesPath:
          - path: "API_KEY"
            objectAlias: "KAFKA_API_KEY"
          - path: "API_SECRET"
            objectAlias: "KAFKA_API_SECRET"
        objectType: "secretsmanager"
      - objectName: "CONFLUENT/schema-registry"
        objectType: "secretsmanager"
        jmesPath:
          - path: "API_KEY"
            objectAlias: "SCHEMA_REGISTRY_API_KEY"
          - path: "API_SECRET"
            objectAlias: "SCHEMA_REGISTRY_API_SECRET"
          - path: "URI"
            objectAlias: "SCHEMA_REGISTRY_URI"
      - objectName: "NEWRELIC_LICENSE"
        objectAlias: "NEW_RELIC_LICENSE_KEY"
        objectType: "secretsmanager"
      - objectName: "dp-person/registry-db"
        jmesPath:
          - path: "username"
            objectAlias: "RDS_DB_USERNAME"
          - path: "password"
            objectAlias: "RDS_DB_PASSWORD"
        objectType: "secretsmanager"

#{{ end }}
